name: Deployer

on: 
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC authentication
  contents: read  # Required to checkout code

jobs:
  deploy_bundle:
    runs-on: ubuntu-latest
    name: 'deploy bundle'
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      # - uses: astral-sh/setup-uv@v1
      - run: databricks bundle deploy
        working-directory: .
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}      
          DATABRICKS_BUNDLE_ENV: dev
