name: Deployer

on: 
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC authentication
  contents: read  # Required to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'update repo folder'
    environment: dev
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Run update Repo
        run: databricks repos update /Workspace/Repos/dartanghan@bouwen.com.br/databricks_test --branch main
      - name: Run update Shared
        run: databricks repos update /Workspace/Shared/databricks_test --branch main
